# Generated by Django 6.0.2 on 2026-02-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_indoor', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
